# Generated by Django 5.2.4 on 2025-07-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='user_id',
            field=models.BigIntegerField(),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
